# 2. Introduction to PyTorch Tensors (pytorch.org)

#### In this second tutorial I will continue to explore PyTorch and see what Tensors are all about. This time i got a full running setup so i got started right away.

In [ ]:
# $ source pytorch_env/Scripts/activate

In [1]:
import torch
import math

#### Creating Tensors

##### `torch.empty()` call:

In [2]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[-6.2937e+06,  1.0286e-42,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


##### This created a 2-dimensional tensor of size 3x4. The values are not initialized and will vary depending on the state of memory. Data types are set by default (float). 
##### A 1-dimensional tensor is a vector
##### A 2-dimensional tensor is a matrix
##### To initialize tensors with some value use `torch` module with its factory methods. For example:

In [3]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


#### Random Tensors and Seeding
##### For reproducibility of results a random number generator's seed is helpful. Use `torch.manual_seed()` to obtain identical results for computations after setting the RNG's seed manually.

In [ ]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729) # setting the seed again will reset the random number generator and obtain the same random numbers
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


#### Tensor Shapes: `torch.*_like()` methods

In [7]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.5062, 0.8469, 0.2588],
         [0.2707, 0.4115, 0.6839]],

        [[0.0703, 0.5105, 0.9451],
         [0.2359, 0.1979, 0.3327]]])


##### Another way to create a tensor is to specify data directly from a PyTorch collection:

In [8]:
some_constants = torch.tensor([[3.1415926, 2.7128], [1.61803, 0.0072897]])
print(some_constants)

tensor([[3.1416, 2.7128],
        [1.6180, 0.0073]])


In [9]:
some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

tensor([ 2,  3,  5,  7, 11, 13, 17, 19])


In [10]:
more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[2, 4, 6],
        [3, 6, 9]])


##### If there is data already present in a tuple or list, `torch.tensor()` is the most straightforward way to create a tensor. Nesting the collections will result in a multi-dimensional tensor.

#### Tensor Data Types

In [ ]:
a = torch.ones((2, 3), dtype=torch.int16) # 16-bit signed integer
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20. # 64-bit floating point
print(b)

c = b.to(torch.int32) # 32-bit signed integer
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.3283,  0.2118, 18.4972],
        [ 9.8370,  3.8937, 16.1945]], dtype=torch.float64)
tensor([[18,  0, 18],
        [ 9,  3, 16]], dtype=torch.int32)


#### Math & Logic with PyTorch Tensors

In [ ]:
# tensor and scalar operations
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [ ]:
# tensor and tensor operations
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

# an important consideration when working with tensors is that the operations are element-wise
# thus the tensors must have the same shape

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


#### Tensor Broadcasting
###### Same rules to broadcasting semantics in NumPy ndarrays
##### Broadcasting is a way to perform an operation between tensors that are similar in shape. In the following example, each row of the `rand` tensor is multiplied by the 1x4 tensor generating a new 2x4 tensor.

In [18]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4)*2)
print(rand)
print(doubled)

tensor([[0.4485, 0.8740, 0.2526, 0.6923],
        [0.7545, 0.7746, 0.2330, 0.8441]])
tensor([[0.8971, 1.7480, 0.5051, 1.3846],
        [1.5091, 1.5491, 0.4660, 1.6881]])


##### A Deep Learning example: multiplying a tensor of learning weights by a batch of input tensors, applying the operation to each instance in the batch separately, returning a tensor with the same shape. 
##### Rules for broadcasting:
###### - Each tensor must have at least one dimension (no empty tensors)
###### - Comparing the dimension sizes of the two tensors, each dimension must be equal or one of the dimensions must be of size 1, or the dimension does not exist in one of the tensors. 
###### - Tensors of identical shape are trivially broadcastable

In [19]:
a =     torch.ones(4, 3, 2)

b = a * torch.rand(   3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

d = a * torch.rand(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.9004, 0.3995],
         [0.6324, 0.9464],
         [0.0113, 0.5183]],

        [[0.9004, 0.3995],
         [0.6324, 0.9464],
         [0.0113, 0.5183]],

        [[0.9004, 0.3995],
         [0.6324, 0.9464],
         [0.0113, 0.5183]],

        [[0.9004, 0.3995],
         [0.6324, 0.9464],
         [0.0113, 0.5183]]])
tensor([[[0.9807, 0.9807],
         [0.6545, 0.6545],
         [0.4144, 0.4144]],

        [[0.9807, 0.9807],
         [0.6545, 0.6545],
         [0.4144, 0.4144]],

        [[0.9807, 0.9807],
         [0.6545, 0.6545],
         [0.4144, 0.4144]],

        [[0.9807, 0.9807],
         [0.6545, 0.6545],
         [0.4144, 0.4144]]])
tensor([[[0.0696, 0.4648],
         [0.0696, 0.4648],
         [0.0696, 0.4648]],

        [[0.0696, 0.4648],
         [0.0696, 0.4648],
         [0.0696, 0.4648]],

        [[0.0696, 0.4648],
         [0.0696, 0.4648],
         [0.0696, 0.4648]],

        [[0.0696, 0.4648],
         [0.0696, 0.4648],
         [0.0696, 0.4648]]])


#### More Math with Tensors

In [20]:
# common functions
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)

# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool

# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements

# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices:')
print(torch.linalg.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.linalg.matmul(m1, m2)
print(m3)                  # 3 times m1
print(torch.linalg.svd(m3))       # singular value decomposition

Common functions:
tensor([[0.1018, 0.2531, 0.8823, 0.0156],
        [0.0921, 0.0792, 0.3893, 0.6054]])
tensor([[-0., 1., 1., -0.],
        [1., 1., -0., -0.]])
tensor([[-1.,  0.,  0., -1.],
        [ 0.,  0., -1., -1.]])
tensor([[-0.1018,  0.2531,  0.5000, -0.0156],
        [ 0.0921,  0.0792, -0.3893, -0.5000]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.3285, 0.5655],
        [0.0065, 0.7765]])
tensor([[0.9856, 1.6966],
        [0.0196, 2.3296]])
torch.return_types.linalg_svd(
U=tensor([[ 0.6345,  0.7729],
        [ 0.7729, -0.6345]]),
S=tensor([2.9475, 0.7677]),
Vh=tensor([[ 0.2173,  0.9761],
        [ 0.9761, -0.2173]

#### Altering Tensors in Place. 
##### When intermediate values of math operations are not needed and can be discarded, math functions have a version ith an appended underscore.

In [21]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))   # this operation creates a new tensor in memory
print(a)              # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))  # note the underscore
print(b)              # b has changed

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [ ]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b)) # the calling tensor a is the one modified in place.
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.3534, 0.7016],
        [0.6826, 0.9413]])

After adding:
tensor([[1.3534, 1.7016],
        [1.6826, 1.9413]])
tensor([[1.3534, 1.7016],
        [1.6826, 1.9413]])
tensor([[0.3534, 0.7016],
        [0.6826, 0.9413]])

After multiplying
tensor([[0.1249, 0.4923],
        [0.4660, 0.8861]])
tensor([[0.1249, 0.4923],
        [0.4660, 0.8861]])


##### Many methods and functions have an `out` argument to specify a tensor to recieve the output (must have the correct shape and dtype).

In [23]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)                # contents of c have changed

assert c is d           # test c & d are same object, not just containing equal values
assert id(c) == old_id  # make sure that our new c is the same object as the old one

torch.rand(2, 2, out=c) # works for creation too!
print(c)                # c has changed again
assert id(c) == old_id  # still the same object!

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.6517, 0.8166],
        [0.5940, 0.7503]])
tensor([[0.4363, 0.6339],
        [0.3208, 0.4323]])


#### Copying Tensors

In [ ]:
# Assigning a tensor to another variable does not create a copy of the tensor
a = torch.ones(2, 2)
b = a
print(a)
a[0][1] = 561  # we change a...
print(b)       # ...and b is also altered

tensor([[1., 1.],
        [1., 1.]])
tensor([[  1., 561.],
        [  1.,   1.]])


##### To copy a tensor is better to use the `clone()` method

In [26]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a # different objects in memory
print(torch.eq(a, b)) # still have the same values
a[0][1] = 561 # we change a...
print(a)
print(b) # ...and b is not altered this time

tensor([[True, True],
        [True, True]])
tensor([[  1., 561.],
        [  1.,   1.]])
tensor([[1., 1.],
        [1., 1.]])


##### When using `clone()`, if the source tensor has autograd enabled, then so will the clone. In case we wanted to avoid the cloned copy to track gradients we can use `.detach()`

In [27]:
a = torch.rand(2, 2, requires_grad=True) # turn on autograd
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)

tensor([[0.1811, 0.6962],
        [0.8073, 0.2125]], requires_grad=True)
tensor([[0.1811, 0.6962],
        [0.8073, 0.2125]], grad_fn=<CloneBackward0>)
tensor([[0.1811, 0.6962],
        [0.8073, 0.2125]])
tensor([[0.1811, 0.6962],
        [0.8073, 0.2125]], requires_grad=True)


#### Moving to Accelerator

##### How do we move to faster hardware like CUDA, MPS, MTIA, or XPU?

In [28]:
if torch.accelerator.is_available():
    print('Accelerator available!')
else:
    print('Sorry, CPU only!')

Accelerator available!


##### To use the accelerator we must move the all the data needed for the specific computation to memory accessible by the device, in this case moving the data to the GPU. By default, new tensors are created on CPU so we have to specify whenever we want to use the accelerator.

In [30]:
if torch.accelerator.is_available():
    gpu_rand = torch.rand(2, 2, device=torch.accelerator.current_accelerator())
    print(gpu_rand)
else:
    print('Sorry, CPU only.')

tensor([[0.6815, 0.0556],
        [0.0711, 0.4825]], device='cuda:0')


##### To query the amount of accelerators we can use `torch.accelerator.device_count()`. If there are more than one accelerator, we can specify them by index: `device='cuda:0'`, `device='cuda:1'`, etc.
##### It is convenient to create a device handle that can be passed to the tensors instead of using a string:

In [ ]:
my_device = torch.accelerator.current_accelerator() if torch.accelerator.is_available() else torch.device('cpu')
print('Device: {}'.format(my_device))

x = torch.rand(2, 2, device=my_device)
print(x)

Device: cuda
tensor([[0.4629, 0.2537],
        [0.0404, 0.0187]], device='cuda:0')


##### When a tensor is created in a specific device it will live there until it is changed to another device with the `to()` method.

In [32]:
y = torch.rand(2, 2) # creates the tensor on the CPU
y = y.to(my_device) # moves the tensor to the GPU

##### To do computation involving two or more tensors, all the tensors must be on the same device.


#### Manipulating Tensor Shapes: Changing number of dimensions
##### Sometimes a model expects batches of input with a certain shape. For example if a model works on 3x226x266 (266px square image with 3 colors), when we load it and transform it we will get a tensor of shape (3, 266, 266). The model will expect input of shape (N, 3, 266, 266), where N is the number of images. We can extend the dimensions using `unsqueeze()` method. Now, if num_batches = 1:

In [34]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0) # adds a dimension at the beginning. A new zeroth index/dimension

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


##### `squeeze()` on the other hand, removes dimensions of size 1. 

In [ ]:
# Examples of squeeze. Removes dimensions of size 1
c = torch.rand(1, 1, 1, 1, 1)
print(c)

a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0) # removes the first dimension
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

tensor([[[[[0.0665]]]]])
torch.Size([1, 20])
tensor([[0.9433, 0.7006, 0.7753, 0.1242, 0.4711, 0.6189, 0.5459, 0.6927, 0.4136,
         0.3063, 0.0856, 0.1923, 0.0667, 0.9678, 0.7519, 0.3056, 0.5590, 0.8477,
         0.9800, 0.3000]])
torch.Size([20])
tensor([0.9433, 0.7006, 0.7753, 0.1242, 0.4711, 0.6189, 0.5459, 0.6927, 0.4136,
        0.3063, 0.0856, 0.1923, 0.0667, 0.9678, 0.7519, 0.3056, 0.5590, 0.8477,
        0.9800, 0.3000])
torch.Size([2, 2])
torch.Size([2, 2])


In [49]:
# Another use of unsqueeze() is to ease broadcasting.
a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # trying to multiply a * b will give a runtime error
c = b.unsqueeze(1)       # change to a 2-dimensional tensor, adding new dim at the end
print(c.shape)
print(a * c)             # broadcasting works again!

torch.Size([3, 1])
tensor([[[0.8337, 0.8337],
         [0.2379, 0.2379],
         [0.9515, 0.9515]],

        [[0.8337, 0.8337],
         [0.2379, 0.2379],
         [0.9515, 0.9515]],

        [[0.8337, 0.8337],
         [0.2379, 0.2379],
         [0.9515, 0.9515]],

        [[0.8337, 0.8337],
         [0.2379, 0.2379],
         [0.9515, 0.9515]]])


In [50]:
# in-place unsqueeze
batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


##### To change the shape of a tensor radically while still preserving the number of elements and their contents we can use `reshape()`.

In [51]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

# can also call it as a method on the torch module:
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


#### NumPy Bridge.
##### Existing ML models or scientific code with stored data in NumPy ndarrays, we can express the same data as PyTorch tensors with `torch.from_numpy()`

In [52]:
import numpy as np

numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


##### The other way around works with `.numpy()` method.

In [53]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.2980, 0.0100, 0.2972],
        [0.9772, 0.9631, 0.0506]])
[[0.2980491  0.00997722 0.2972157 ]
 [0.9772248  0.96310294 0.05055839]]


##### Once finished this tutorial I feel like I understood the nature of tensors better than before. Very useful operations and methods, with a lot of potential. I like that data can be stored in them and that PyTorch allows the use of GPU on command for faster computations. Luckily my notebook can use CUDA so I will be able to use this feature in my models. I am thrilled about learning PyTorch and I'm excited to keep exploring the capabilities of this technology.
##### - Arturo